// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tc_message.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_tc_5fmessage_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_tc_5fmessage_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_bases.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_tc_5fmessage_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_tc_5fmessage_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_tc_5fmessage_2eproto;
namespace tc {
class Ack;
struct AckDefaultTypeInternal;
extern AckDefaultTypeInternal _Ack_default_instance_;
class AudioFrame;
struct AudioFrameDefaultTypeInternal;
extern AudioFrameDefaultTypeInternal _AudioFrame_default_instance_;
class HeartBeat;
struct HeartBeatDefaultTypeInternal;
extern HeartBeatDefaultTypeInternal _HeartBeat_default_instance_;
class Hello;
struct HelloDefaultTypeInternal;
extern HelloDefaultTypeInternal _Hello_default_instance_;
class Message;
struct MessageDefaultTypeInternal;
extern MessageDefaultTypeInternal _Message_default_instance_;
class VideoFrame;
struct VideoFrameDefaultTypeInternal;
extern VideoFrameDefaultTypeInternal _VideoFrame_default_instance_;
}  // namespace tc
PROTOBUF_NAMESPACE_OPEN
template<> ::tc::Ack* Arena::CreateMaybeMessage<::tc::Ack>(Arena*);
template<> ::tc::AudioFrame* Arena::CreateMaybeMessage<::tc::AudioFrame>(Arena*);
template<> ::tc::HeartBeat* Arena::CreateMaybeMessage<::tc::HeartBeat>(Arena*);
template<> ::tc::Hello* Arena::CreateMaybeMessage<::tc::Hello>(Arena*);
template<> ::tc::Message* Arena::CreateMaybeMessage<::tc::Message>(Arena*);
template<> ::tc::VideoFrame* Arena::CreateMaybeMessage<::tc::VideoFrame>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace tc {

enum MessageType : int {
  kHello = 0,
  kAck = 1,
  kHeartBeat = 2,
  kVideoFrame = 3,
  kAudioFrame = 4,
  MessageType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  MessageType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool MessageType_IsValid(int value);
constexpr MessageType MessageType_MIN = kHello;
constexpr MessageType MessageType_MAX = kAudioFrame;
constexpr int MessageType_ARRAYSIZE = MessageType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MessageType_descriptor();
template<typename T>
inline const std::string& MessageType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, MessageType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function MessageType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    MessageType_descriptor(), enum_t_value);
}
inline bool MessageType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, MessageType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<MessageType>(
    MessageType_descriptor(), name, value);
}
enum VideoType : int {
  kNetH264 = 0,
  kNetHevc = 1,
  kNetVp9 = 2,
  VideoType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  VideoType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool VideoType_IsValid(int value);
constexpr VideoType VideoType_MIN = kNetH264;
constexpr VideoType VideoType_MAX = kNetVp9;
constexpr int VideoType_ARRAYSIZE = VideoType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* VideoType_descriptor();
template<typename T>
inline const std::string& VideoType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, VideoType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function VideoType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    VideoType_descriptor(), enum_t_value);
}
inline bool VideoType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, VideoType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<VideoType>(
    VideoType_descriptor(), name, value);
}
// ===================================================================

class Ack final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:tc.Ack) */ {
 public:
  inline Ack() : Ack(nullptr) {}
  ~Ack() override;
  explicit PROTOBUF_CONSTEXPR Ack(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Ack(const Ack& from);
  Ack(Ack&& from) noexcept
    : Ack() {
    *this = ::std::move(from);
  }

  inline Ack& operator=(const Ack& from) {
    CopyFrom(from);
    return *this;
  }
  inline Ack& operator=(Ack&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Ack& default_instance() {
    return *internal_default_instance();
  }
  static inline const Ack* internal_default_instance() {
    return reinterpret_cast<const Ack*>(
               &_Ack_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Ack& a, Ack& b) {
    a.Swap(&b);
  }
  inline void Swap(Ack* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Ack* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Ack* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Ack>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Ack& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Ack& from) {
    Ack::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Ack* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "tc.Ack";
  }
  protected:
  explicit Ack(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSendTimeFieldNumber = 2,
    kTypeFieldNumber = 1,
  };
  // uint64 send_time = 2;
  void clear_send_time();
  uint64_t send_time() const;
  void set_send_time(uint64_t value);
  private:
  uint64_t _internal_send_time() const;
  void _internal_set_send_time(uint64_t value);
  public:

  // .tc.MessageType type = 1;
  void clear_type();
  ::tc::MessageType type() const;
  void set_type(::tc::MessageType value);
  private:
  ::tc::MessageType _internal_type() const;
  void _internal_set_type(::tc::MessageType value);
  public:

  // @@protoc_insertion_point(class_scope:tc.Ack)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t send_time_;
    int type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_tc_5fmessage_2eproto;
};
// -------------------------------------------------------------------

class Hello final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:tc.Hello) */ {
 public:
  inline Hello() : Hello(nullptr) {}
  explicit PROTOBUF_CONSTEXPR Hello(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Hello(const Hello& from);
  Hello(Hello&& from) noexcept
    : Hello() {
    *this = ::std::move(from);
  }

  inline Hello& operator=(const Hello& from) {
    CopyFrom(from);
    return *this;
  }
  inline Hello& operator=(Hello&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Hello& default_instance() {
    return *internal_default_instance();
  }
  static inline const Hello* internal_default_instance() {
    return reinterpret_cast<const Hello*>(
               &_Hello_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Hello& a, Hello& b) {
    a.Swap(&b);
  }
  inline void Swap(Hello* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Hello* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Hello* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Hello>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const Hello& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const Hello& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "tc.Hello";
  }
  protected:
  explicit Hello(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:tc.Hello)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_tc_5fmessage_2eproto;
};
// -------------------------------------------------------------------

class HeartBeat final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:tc.HeartBeat) */ {
 public:
  inline HeartBeat() : HeartBeat(nullptr) {}
  explicit PROTOBUF_CONSTEXPR HeartBeat(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  HeartBeat(const HeartBeat& from);
  HeartBeat(HeartBeat&& from) noexcept
    : HeartBeat() {
    *this = ::std::move(from);
  }

  inline HeartBeat& operator=(const HeartBeat& from) {
    CopyFrom(from);
    return *this;
  }
  inline HeartBeat& operator=(HeartBeat&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HeartBeat& default_instance() {
    return *internal_default_instance();
  }
  static inline const HeartBeat* internal_default_instance() {
    return reinterpret_cast<const HeartBeat*>(
               &_HeartBeat_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(HeartBeat& a, HeartBeat& b) {
    a.Swap(&b);
  }
  inline void Swap(HeartBeat* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HeartBeat* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HeartBeat* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<HeartBeat>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const HeartBeat& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const HeartBeat& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "tc.HeartBeat";
  }
  protected:
  explicit HeartBeat(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:tc.HeartBeat)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_tc_5fmessage_2eproto;
};
// -------------------------------------------------------------------

class VideoFrame final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:tc.VideoFrame) */ {
 public:
  inline VideoFrame() : VideoFrame(nullptr) {}
  ~VideoFrame() override;
  explicit PROTOBUF_CONSTEXPR VideoFrame(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  VideoFrame(const VideoFrame& from);
  VideoFrame(VideoFrame&& from) noexcept
    : VideoFrame() {
    *this = ::std::move(from);
  }

  inline VideoFrame& operator=(const VideoFrame& from) {
    CopyFrom(from);
    return *this;
  }
  inline VideoFrame& operator=(VideoFrame&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const VideoFrame& default_instance() {
    return *internal_default_instance();
  }
  static inline const VideoFrame* internal_default_instance() {
    return reinterpret_cast<const VideoFrame*>(
               &_VideoFrame_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(VideoFrame& a, VideoFrame& b) {
    a.Swap(&b);
  }
  inline void Swap(VideoFrame* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VideoFrame* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VideoFrame* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<VideoFrame>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const VideoFrame& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const VideoFrame& from) {
    VideoFrame::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(VideoFrame* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "tc.VideoFrame";
  }
  protected:
  explicit VideoFrame(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 2,
    kTypeFieldNumber = 1,
    kKeyFieldNumber = 4,
    kFrameIndexFieldNumber = 3,
    kFrameWidthFieldNumber = 5,
    kFrameHeightFieldNumber = 6,
  };
  // bytes data = 2;
  void clear_data();
  const std::string& data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_data();
  PROTOBUF_NODISCARD std::string* release_data();
  void set_allocated_data(std::string* data);
  private:
  const std::string& _internal_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  // .tc.VideoType type = 1;
  void clear_type();
  ::tc::VideoType type() const;
  void set_type(::tc::VideoType value);
  private:
  ::tc::VideoType _internal_type() const;
  void _internal_set_type(::tc::VideoType value);
  public:

  // bool key = 4;
  void clear_key();
  bool key() const;
  void set_key(bool value);
  private:
  bool _internal_key() const;
  void _internal_set_key(bool value);
  public:

  // uint64 frame_index = 3;
  void clear_frame_index();
  uint64_t frame_index() const;
  void set_frame_index(uint64_t value);
  private:
  uint64_t _internal_frame_index() const;
  void _internal_set_frame_index(uint64_t value);
  public:

  // int32 frame_width = 5;
  void clear_frame_width();
  int32_t frame_width() const;
  void set_frame_width(int32_t value);
  private:
  int32_t _internal_frame_width() const;
  void _internal_set_frame_width(int32_t value);
  public:

  // int32 frame_height = 6;
  void clear_frame_height();
  int32_t frame_height() const;
  void set_frame_height(int32_t value);
  private:
  int32_t _internal_frame_height() const;
  void _internal_set_frame_height(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:tc.VideoFrame)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
    int type_;
    bool key_;
    uint64_t frame_index_;
    int32_t frame_width_;
    int32_t frame_height_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_tc_5fmessage_2eproto;
};
// -------------------------------------------------------------------

class AudioFrame final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:tc.AudioFrame) */ {
 public:
  inline AudioFrame() : AudioFrame(nullptr) {}
  ~AudioFrame() override;
  explicit PROTOBUF_CONSTEXPR AudioFrame(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AudioFrame(const AudioFrame& from);
  AudioFrame(AudioFrame&& from) noexcept
    : AudioFrame() {
    *this = ::std::move(from);
  }

  inline AudioFrame& operator=(const AudioFrame& from) {
    CopyFrom(from);
    return *this;
  }
  inline AudioFrame& operator=(AudioFrame&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AudioFrame& default_instance() {
    return *internal_default_instance();
  }
  static inline const AudioFrame* internal_default_instance() {
    return reinterpret_cast<const AudioFrame*>(
               &_AudioFrame_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(AudioFrame& a, AudioFrame& b) {
    a.Swap(&b);
  }
  inline void Swap(AudioFrame* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AudioFrame* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AudioFrame* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AudioFrame>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AudioFrame& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AudioFrame& from) {
    AudioFrame::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AudioFrame* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "tc.AudioFrame";
  }
  protected:
  explicit AudioFrame(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 3,
    kSamplesFieldNumber = 1,
    kChannelsFieldNumber = 2,
  };
  // bytes data = 3;
  void clear_data();
  const std::string& data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_data();
  PROTOBUF_NODISCARD std::string* release_data();
  void set_allocated_data(std::string* data);
  private:
  const std::string& _internal_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  // int32 samples = 1;
  void clear_samples();
  int32_t samples() const;
  void set_samples(int32_t value);
  private:
  int32_t _internal_samples() const;
  void _internal_set_samples(int32_t value);
  public:

  // int32 channels = 2;
  void clear_channels();
  int32_t channels() const;
  void set_channels(int32_t value);
  private:
  int32_t _internal_channels() const;
  void _internal_set_channels(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:tc.AudioFrame)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
    int32_t samples_;
    int32_t channels_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_tc_5fmessage_2eproto;
};
// -------------------------------------------------------------------

class Message final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:tc.Message) */ {
 public:
  inline Message() : Message(nullptr) {}
  ~Message() override;
  explicit PROTOBUF_CONSTEXPR Message(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Message(const Message& from);
  Message(Message&& from) noexcept
    : Message() {
    *this = ::std::move(from);
  }

  inline Message& operator=(const Message& from) {
    CopyFrom(from);
    return *this;
  }
  inline Message& operator=(Message&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Message& default_instance() {
    return *internal_default_instance();
  }
  static inline const Message* internal_default_instance() {
    return reinterpret_cast<const Message*>(
               &_Message_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(Message& a, Message& b) {
    a.Swap(&b);
  }
  inline void Swap(Message* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Message* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Message* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Message>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Message& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Message& from) {
    Message::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Message* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "tc.Message";
  }
  protected:
  explicit Message(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHelloFieldNumber = 3,
    kAckFieldNumber = 4,
    kHeartBeatFieldNumber = 5,
    kVideoFrameFieldNumber = 6,
    kAudioFrameFieldNumber = 7,
    kSendTimeFieldNumber = 2,
    kTypeFieldNumber = 1,
  };
  // .tc.Hello hello = 3;
  bool has_hello() const;
  private:
  bool _internal_has_hello() const;
  public:
  void clear_hello();
  const ::tc::Hello& hello() const;
  PROTOBUF_NODISCARD ::tc::Hello* release_hello();
  ::tc::Hello* mutable_hello();
  void set_allocated_hello(::tc::Hello* hello);
  private:
  const ::tc::Hello& _internal_hello() const;
  ::tc::Hello* _internal_mutable_hello();
  public:
  void unsafe_arena_set_allocated_hello(
      ::tc::Hello* hello);
  ::tc::Hello* unsafe_arena_release_hello();

  // .tc.Ack ack = 4;
  bool has_ack() const;
  private:
  bool _internal_has_ack() const;
  public:
  void clear_ack();
  const ::tc::Ack& ack() const;
  PROTOBUF_NODISCARD ::tc::Ack* release_ack();
  ::tc::Ack* mutable_ack();
  void set_allocated_ack(::tc::Ack* ack);
  private:
  const ::tc::Ack& _internal_ack() const;
  ::tc::Ack* _internal_mutable_ack();
  public:
  void unsafe_arena_set_allocated_ack(
      ::tc::Ack* ack);
  ::tc::Ack* unsafe_arena_release_ack();

  // .tc.HeartBeat heart_beat = 5;
  bool has_heart_beat() const;
  private:
  bool _internal_has_heart_beat() const;
  public:
  void clear_heart_beat();
  const ::tc::HeartBeat& heart_beat() const;
  PROTOBUF_NODISCARD ::tc::HeartBeat* release_heart_beat();
  ::tc::HeartBeat* mutable_heart_beat();
  void set_allocated_heart_beat(::tc::HeartBeat* heart_beat);
  private:
  const ::tc::HeartBeat& _internal_heart_beat() const;
  ::tc::HeartBeat* _internal_mutable_heart_beat();
  public:
  void unsafe_arena_set_allocated_heart_beat(
      ::tc::HeartBeat* heart_beat);
  ::tc::HeartBeat* unsafe_arena_release_heart_beat();

  // .tc.VideoFrame video_frame = 6;
  bool has_video_frame() const;
  private:
  bool _internal_has_video_frame() const;
  public:
  void clear_video_frame();
  const ::tc::VideoFrame& video_frame() const;
  PROTOBUF_NODISCARD ::tc::VideoFrame* release_video_frame();
  ::tc::VideoFrame* mutable_video_frame();
  void set_allocated_video_frame(::tc::VideoFrame* video_frame);
  private:
  const ::tc::VideoFrame& _internal_video_frame() const;
  ::tc::VideoFrame* _internal_mutable_video_frame();
  public:
  void unsafe_arena_set_allocated_video_frame(
      ::tc::VideoFrame* video_frame);
  ::tc::VideoFrame* unsafe_arena_release_video_frame();

  // .tc.AudioFrame audio_frame = 7;
  bool has_audio_frame() const;
  private:
  bool _internal_has_audio_frame() const;
  public:
  void clear_audio_frame();
  const ::tc::AudioFrame& audio_frame() const;
  PROTOBUF_NODISCARD ::tc::AudioFrame* release_audio_frame();
  ::tc::AudioFrame* mutable_audio_frame();
  void set_allocated_audio_frame(::tc::AudioFrame* audio_frame);
  private:
  const ::tc::AudioFrame& _internal_audio_frame() const;
  ::tc::AudioFrame* _internal_mutable_audio_frame();
  public:
  void unsafe_arena_set_allocated_audio_frame(
      ::tc::AudioFrame* audio_frame);
  ::tc::AudioFrame* unsafe_arena_release_audio_frame();

  // uint64 send_time = 2;
  void clear_send_time();
  uint64_t send_time() const;
  void set_send_time(uint64_t value);
  private:
  uint64_t _internal_send_time() const;
  void _internal_set_send_time(uint64_t value);
  public:

  // .tc.MessageType type = 1;
  void clear_type();
  ::tc::MessageType type() const;
  void set_type(::tc::MessageType value);
  private:
  ::tc::MessageType _internal_type() const;
  void _internal_set_type(::tc::MessageType value);
  public:

  // @@protoc_insertion_point(class_scope:tc.Message)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::tc::Hello* hello_;
    ::tc::Ack* ack_;
    ::tc::HeartBeat* heart_beat_;
    ::tc::VideoFrame* video_frame_;
    ::tc::AudioFrame* audio_frame_;
    uint64_t send_time_;
    int type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_tc_5fmessage_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Ack

// .tc.MessageType type = 1;
inline void Ack::clear_type() {
  _impl_.type_ = 0;
}
inline ::tc::MessageType Ack::_internal_type() const {
  return static_cast< ::tc::MessageType >(_impl_.type_);
}
inline ::tc::MessageType Ack::type() const {
  // @@protoc_insertion_point(field_get:tc.Ack.type)
  return _internal_type();
}
inline void Ack::_internal_set_type(::tc::MessageType value) {
  
  _impl_.type_ = value;
}
inline void Ack::set_type(::tc::MessageType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:tc.Ack.type)
}

// uint64 send_time = 2;
inline void Ack::clear_send_time() {
  _impl_.send_time_ = uint64_t{0u};
}
inline uint64_t Ack::_internal_send_time() const {
  return _impl_.send_time_;
}
inline uint64_t Ack::send_time() const {
  // @@protoc_insertion_point(field_get:tc.Ack.send_time)
  return _internal_send_time();
}
inline void Ack::_internal_set_send_time(uint64_t value) {
  
  _impl_.send_time_ = value;
}
inline void Ack::set_send_time(uint64_t value) {
  _internal_set_send_time(value);
  // @@protoc_insertion_point(field_set:tc.Ack.send_time)
}

// -------------------------------------------------------------------

// Hello

// -------------------------------------------------------------------

// HeartBeat

// -------------------------------------------------------------------

// VideoFrame

// .tc.VideoType type = 1;
inline void VideoFrame::clear_type() {
  _impl_.type_ = 0;
}
inline ::tc::VideoType VideoFrame::_internal_type() const {
  return static_cast< ::tc::VideoType >(_impl_.type_);
}
inline ::tc::VideoType VideoFrame::type() const {
  // @@protoc_insertion_point(field_get:tc.VideoFrame.type)
  return _internal_type();
}
inline void VideoFrame::_internal_set_type(::tc::VideoType value) {
  
  _impl_.type_ = value;
}
inline void VideoFrame::set_type(::tc::VideoType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:tc.VideoFrame.type)
}

// bytes data = 2;
inline void VideoFrame::clear_data() {
  _impl_.data_.ClearToEmpty();
}
inline const std::string& VideoFrame::data() const {
  // @@protoc_insertion_point(field_get:tc.VideoFrame.data)
  return _internal_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void VideoFrame::set_data(ArgT0&& arg0, ArgT... args) {
 
 _impl_.data_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:tc.VideoFrame.data)
}
inline std::string* VideoFrame::mutable_data() {
  std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:tc.VideoFrame.data)
  return _s;
}
inline const std::string& VideoFrame::_internal_data() const {
  return _impl_.data_.Get();
}
inline void VideoFrame::_internal_set_data(const std::string& value) {
  
  _impl_.data_.Set(value, GetArenaForAllocation());
}
inline std::string* VideoFrame::_internal_mutable_data() {
  
  return _impl_.data_.Mutable(GetArenaForAllocation());
}
inline std::string* VideoFrame::release_data() {
  // @@protoc_insertion_point(field_release:tc.VideoFrame.data)
  return _impl_.data_.Release();
}
inline void VideoFrame::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    
  } else {
    
  }
  _impl_.data_.SetAllocated(data, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.data_.IsDefault()) {
    _impl_.data_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:tc.VideoFrame.data)
}

// uint64 frame_index = 3;
inline void VideoFrame::clear_frame_index() {
  _impl_.frame_index_ = uint64_t{0u};
}
inline uint64_t VideoFrame::_internal_frame_index() const {
  return _impl_.frame_index_;
}
inline uint64_t VideoFrame::frame_index() const {
  // @@protoc_insertion_point(field_get:tc.VideoFrame.frame_index)
  return _internal_frame_index();
}
inline void VideoFrame::_internal_set_frame_index(uint64_t value) {
  
  _impl_.frame_index_ = value;
}
inline void VideoFrame::set_frame_index(uint64_t value) {
  _internal_set_frame_index(value);
  // @@protoc_insertion_point(field_set:tc.VideoFrame.frame_index)
}

// bool key = 4;
inline void VideoFrame::clear_key() {
  _impl_.key_ = false;
}
inline bool VideoFrame::_internal_key() const {
  return _impl_.key_;
}
inline bool VideoFrame::key() const {
  // @@protoc_insertion_point(field_get:tc.VideoFrame.key)
  return _internal_key();
}
inline void VideoFrame::_internal_set_key(bool value) {
  
  _impl_.key_ = value;
}
inline void VideoFrame::set_key(bool value) {
  _internal_set_key(value);
  // @@protoc_insertion_point(field_set:tc.VideoFrame.key)
}

// int32 frame_width = 5;
inline void VideoFrame::clear_frame_width() {
  _impl_.frame_width_ = 0;
}
inline int32_t VideoFrame::_internal_frame_width() const {
  return _impl_.frame_width_;
}
inline int32_t VideoFrame::frame_width() const {
  // @@protoc_insertion_point(field_get:tc.VideoFrame.frame_width)
  return _internal_frame_width();
}
inline void VideoFrame::_internal_set_frame_width(int32_t value) {
  
  _impl_.frame_width_ = value;
}
inline void VideoFrame::set_frame_width(int32_t value) {
  _internal_set_frame_width(value);
  // @@protoc_insertion_point(field_set:tc.VideoFrame.frame_width)
}

// int32 frame_height = 6;
inline void VideoFrame::clear_frame_height() {
  _impl_.frame_height_ = 0;
}
inline int32_t VideoFrame::_internal_frame_height() const {
  return _impl_.frame_height_;
}
inline int32_t VideoFrame::frame_height() const {
  // @@protoc_insertion_point(field_get:tc.VideoFrame.frame_height)
  return _internal_frame_height();
}
inline void VideoFrame::_internal_set_frame_height(int32_t value) {
  
  _impl_.frame_height_ = value;
}
inline void VideoFrame::set_frame_height(int32_t value) {
  _internal_set_frame_height(value);
  // @@protoc_insertion_point(field_set:tc.VideoFrame.frame_height)
}

// -------------------------------------------------------------------

// AudioFrame

// int32 samples = 1;
inline void AudioFrame::clear_samples() {
  _impl_.samples_ = 0;
}
inline int32_t AudioFrame::_internal_samples() const {
  return _impl_.samples_;
}
inline int32_t AudioFrame::samples() const {
  // @@protoc_insertion_point(field_get:tc.AudioFrame.samples)
  return _internal_samples();
}
inline void AudioFrame::_internal_set_samples(int32_t value) {
  
  _impl_.samples_ = value;
}
inline void AudioFrame::set_samples(int32_t value) {
  _internal_set_samples(value);
  // @@protoc_insertion_point(field_set:tc.AudioFrame.samples)
}

// int32 channels = 2;
inline void AudioFrame::clear_channels() {
  _impl_.channels_ = 0;
}
inline int32_t AudioFrame::_internal_channels() const {
  return _impl_.channels_;
}
inline int32_t AudioFrame::channels() const {
  // @@protoc_insertion_point(field_get:tc.AudioFrame.channels)
  return _internal_channels();
}
inline void AudioFrame::_internal_set_channels(int32_t value) {
  
  _impl_.channels_ = value;
}
inline void AudioFrame::set_channels(int32_t value) {
  _internal_set_channels(value);
  // @@protoc_insertion_point(field_set:tc.AudioFrame.channels)
}

// bytes data = 3;
inline void AudioFrame::clear_data() {
  _impl_.data_.ClearToEmpty();
}
inline const std::string& AudioFrame::data() const {
  // @@protoc_insertion_point(field_get:tc.AudioFrame.data)
  return _internal_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AudioFrame::set_data(ArgT0&& arg0, ArgT... args) {
 
 _impl_.data_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:tc.AudioFrame.data)
}
inline std::string* AudioFrame::mutable_data() {
  std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:tc.AudioFrame.data)
  return _s;
}
inline const std::string& AudioFrame::_internal_data() const {
  return _impl_.data_.Get();
}
inline void AudioFrame::_internal_set_data(const std::string& value) {
  
  _impl_.data_.Set(value, GetArenaForAllocation());
}
inline std::string* AudioFrame::_internal_mutable_data() {
  
  return _impl_.data_.Mutable(GetArenaForAllocation());
}
inline std::string* AudioFrame::release_data() {
  // @@protoc_insertion_point(field_release:tc.AudioFrame.data)
  return _impl_.data_.Release();
}
inline void AudioFrame::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    
  } else {
    
  }
  _impl_.data_.SetAllocated(data, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.data_.IsDefault()) {
    _impl_.data_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:tc.AudioFrame.data)
}

// -------------------------------------------------------------------

// Message

// .tc.MessageType type = 1;
inline void Message::clear_type() {
  _impl_.type_ = 0;
}
inline ::tc::MessageType Message::_internal_type() const {
  return static_cast< ::tc::MessageType >(_impl_.type_);
}
inline ::tc::MessageType Message::type() const {
  // @@protoc_insertion_point(field_get:tc.Message.type)
  return _internal_type();
}
inline void Message::_internal_set_type(::tc::MessageType value) {
  
  _impl_.type_ = value;
}
inline void Message::set_type(::tc::MessageType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:tc.Message.type)
}

// uint64 send_time = 2;
inline void Message::clear_send_time() {
  _impl_.send_time_ = uint64_t{0u};
}
inline uint64_t Message::_internal_send_time() const {
  return _impl_.send_time_;
}
inline uint64_t Message::send_time() const {
  // @@protoc_insertion_point(field_get:tc.Message.send_time)
  return _internal_send_time();
}
inline void Message::_internal_set_send_time(uint64_t value) {
  
  _impl_.send_time_ = value;
}
inline void Message::set_send_time(uint64_t value) {
  _internal_set_send_time(value);
  // @@protoc_insertion_point(field_set:tc.Message.send_time)
}

// .tc.Hello hello = 3;
inline bool Message::_internal_has_hello() const {
  return this != internal_default_instance() && _impl_.hello_ != nullptr;
}
inline bool Message::has_hello() const {
  return _internal_has_hello();
}
inline void Message::clear_hello() {
  if (GetArenaForAllocation() == nullptr && _impl_.hello_ != nullptr) {
    delete _impl_.hello_;
  }
  _impl_.hello_ = nullptr;
}
inline const ::tc::Hello& Message::_internal_hello() const {
  const ::tc::Hello* p = _impl_.hello_;
  return p != nullptr ? *p : reinterpret_cast<const ::tc::Hello&>(
      ::tc::_Hello_default_instance_);
}
inline const ::tc::Hello& Message::hello() const {
  // @@protoc_insertion_point(field_get:tc.Message.hello)
  return _internal_hello();
}
inline void Message::unsafe_arena_set_allocated_hello(
    ::tc::Hello* hello) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.hello_);
  }
  _impl_.hello_ = hello;
  if (hello) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:tc.Message.hello)
}
inline ::tc::Hello* Message::release_hello() {
  
  ::tc::Hello* temp = _impl_.hello_;
  _impl_.hello_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::tc::Hello* Message::unsafe_arena_release_hello() {
  // @@protoc_insertion_point(field_release:tc.Message.hello)
  
  ::tc::Hello* temp = _impl_.hello_;
  _impl_.hello_ = nullptr;
  return temp;
}
inline ::tc::Hello* Message::_internal_mutable_hello() {
  
  if (_impl_.hello_ == nullptr) {
    auto* p = CreateMaybeMessage<::tc::Hello>(GetArenaForAllocation());
    _impl_.hello_ = p;
  }
  return _impl_.hello_;
}
inline ::tc::Hello* Message::mutable_hello() {
  ::tc::Hello* _msg = _internal_mutable_hello();
  // @@protoc_insertion_point(field_mutable:tc.Message.hello)
  return _msg;
}
inline void Message::set_allocated_hello(::tc::Hello* hello) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.hello_;
  }
  if (hello) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(hello);
    if (message_arena != submessage_arena) {
      hello = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, hello, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.hello_ = hello;
  // @@protoc_insertion_point(field_set_allocated:tc.Message.hello)
}

// .tc.Ack ack = 4;
inline bool Message::_internal_has_ack() const {
  return this != internal_default_instance() && _impl_.ack_ != nullptr;
}
inline bool Message::has_ack() const {
  return _internal_has_ack();
}
inline void Message::clear_ack() {
  if (GetArenaForAllocation() == nullptr && _impl_.ack_ != nullptr) {
    delete _impl_.ack_;
  }
  _impl_.ack_ = nullptr;
}
inline const ::tc::Ack& Message::_internal_ack() const {
  const ::tc::Ack* p = _impl_.ack_;
  return p != nullptr ? *p : reinterpret_cast<const ::tc::Ack&>(
      ::tc::_Ack_default_instance_);
}
inline const ::tc::Ack& Message::ack() const {
  // @@protoc_insertion_point(field_get:tc.Message.ack)
  return _internal_ack();
}
inline void Message::unsafe_arena_set_allocated_ack(
    ::tc::Ack* ack) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.ack_);
  }
  _impl_.ack_ = ack;
  if (ack) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:tc.Message.ack)
}
inline ::tc::Ack* Message::release_ack() {
  
  ::tc::Ack* temp = _impl_.ack_;
  _impl_.ack_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::tc::Ack* Message::unsafe_arena_release_ack() {
  // @@protoc_insertion_point(field_release:tc.Message.ack)
  
  ::tc::Ack* temp = _impl_.ack_;
  _impl_.ack_ = nullptr;
  return temp;
}
inline ::tc::Ack* Message::_internal_mutable_ack() {
  
  if (_impl_.ack_ == nullptr) {
    auto* p = CreateMaybeMessage<::tc::Ack>(GetArenaForAllocation());
    _impl_.ack_ = p;
  }
  return _impl_.ack_;
}
inline ::tc::Ack* Message::mutable_ack() {
  ::tc::Ack* _msg = _internal_mutable_ack();
  // @@protoc_insertion_point(field_mutable:tc.Message.ack)
  return _msg;
}
inline void Message::set_allocated_ack(::tc::Ack* ack) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.ack_;
  }
  if (ack) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(ack);
    if (message_arena != submessage_arena) {
      ack = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, ack, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.ack_ = ack;
  // @@protoc_insertion_point(field_set_allocated:tc.Message.ack)
}

// .tc.HeartBeat heart_beat = 5;
inline bool Message::_internal_has_heart_beat() const {
  return this != internal_default_instance() && _impl_.heart_beat_ != nullptr;
}
inline bool Message::has_heart_beat() const {
  return _internal_has_heart_beat();
}
inline void Message::clear_heart_beat() {
  if (GetArenaForAllocation() == nullptr && _impl_.heart_beat_ != nullptr) {
    delete _impl_.heart_beat_;
  }
  _impl_.heart_beat_ = nullptr;
}
inline const ::tc::HeartBeat& Message::_internal_heart_beat() const {
  const ::tc::HeartBeat* p = _impl_.heart_beat_;
  return p != nullptr ? *p : reinterpret_cast<const ::tc::HeartBeat&>(
      ::tc::_HeartBeat_default_instance_);
}
inline const ::tc::HeartBeat& Message::heart_beat() const {
  // @@protoc_insertion_point(field_get:tc.Message.heart_beat)
  return _internal_heart_beat();
}
inline void Message::unsafe_arena_set_allocated_heart_beat(
    ::tc::HeartBeat* heart_beat) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.heart_beat_);
  }
  _impl_.heart_beat_ = heart_beat;
  if (heart_beat) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:tc.Message.heart_beat)
}
inline ::tc::HeartBeat* Message::release_heart_beat() {
  
  ::tc::HeartBeat* temp = _impl_.heart_beat_;
  _impl_.heart_beat_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::tc::HeartBeat* Message::unsafe_arena_release_heart_beat() {
  // @@protoc_insertion_point(field_release:tc.Message.heart_beat)
  
  ::tc::HeartBeat* temp = _impl_.heart_beat_;
  _impl_.heart_beat_ = nullptr;
  return temp;
}
inline ::tc::HeartBeat* Message::_internal_mutable_heart_beat() {
  
  if (_impl_.heart_beat_ == nullptr) {
    auto* p = CreateMaybeMessage<::tc::HeartBeat>(GetArenaForAllocation());
    _impl_.heart_beat_ = p;
  }
  return _impl_.heart_beat_;
}
inline ::tc::HeartBeat* Message::mutable_heart_beat() {
  ::tc::HeartBeat* _msg = _internal_mutable_heart_beat();
  // @@protoc_insertion_point(field_mutable:tc.Message.heart_beat)
  return _msg;
}
inline void Message::set_allocated_heart_beat(::tc::HeartBeat* heart_beat) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.heart_beat_;
  }
  if (heart_beat) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(heart_beat);
    if (message_arena != submessage_arena) {
      heart_beat = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, heart_beat, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.heart_beat_ = heart_beat;
  // @@protoc_insertion_point(field_set_allocated:tc.Message.heart_beat)
}

// .tc.VideoFrame video_frame = 6;
inline bool Message::_internal_has_video_frame() const {
  return this != internal_default_instance() && _impl_.video_frame_ != nullptr;
}
inline bool Message::has_video_frame() const {
  return _internal_has_video_frame();
}
inline void Message::clear_video_frame() {
  if (GetArenaForAllocation() == nullptr && _impl_.video_frame_ != nullptr) {
    delete _impl_.video_frame_;
  }
  _impl_.video_frame_ = nullptr;
}
inline const ::tc::VideoFrame& Message::_internal_video_frame() const {
  const ::tc::VideoFrame* p = _impl_.video_frame_;
  return p != nullptr ? *p : reinterpret_cast<const ::tc::VideoFrame&>(
      ::tc::_VideoFrame_default_instance_);
}
inline const ::tc::VideoFrame& Message::video_frame() const {
  // @@protoc_insertion_point(field_get:tc.Message.video_frame)
  return _internal_video_frame();
}
inline void Message::unsafe_arena_set_allocated_video_frame(
    ::tc::VideoFrame* video_frame) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.video_frame_);
  }
  _impl_.video_frame_ = video_frame;
  if (video_frame) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:tc.Message.video_frame)
}
inline ::tc::VideoFrame* Message::release_video_frame() {
  
  ::tc::VideoFrame* temp = _impl_.video_frame_;
  _impl_.video_frame_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::tc::VideoFrame* Message::unsafe_arena_release_video_frame() {
  // @@protoc_insertion_point(field_release:tc.Message.video_frame)
  
  ::tc::VideoFrame* temp = _impl_.video_frame_;
  _impl_.video_frame_ = nullptr;
  return temp;
}
inline ::tc::VideoFrame* Message::_internal_mutable_video_frame() {
  
  if (_impl_.video_frame_ == nullptr) {
    auto* p = CreateMaybeMessage<::tc::VideoFrame>(GetArenaForAllocation());
    _impl_.video_frame_ = p;
  }
  return _impl_.video_frame_;
}
inline ::tc::VideoFrame* Message::mutable_video_frame() {
  ::tc::VideoFrame* _msg = _internal_mutable_video_frame();
  // @@protoc_insertion_point(field_mutable:tc.Message.video_frame)
  return _msg;
}
inline void Message::set_allocated_video_frame(::tc::VideoFrame* video_frame) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.video_frame_;
  }
  if (video_frame) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(video_frame);
    if (message_arena != submessage_arena) {
      video_frame = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, video_frame, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.video_frame_ = video_frame;
  // @@protoc_insertion_point(field_set_allocated:tc.Message.video_frame)
}

// .tc.AudioFrame audio_frame = 7;
inline bool Message::_internal_has_audio_frame() const {
  return this != internal_default_instance() && _impl_.audio_frame_ != nullptr;
}
inline bool Message::has_audio_frame() const {
  return _internal_has_audio_frame();
}
inline void Message::clear_audio_frame() {
  if (GetArenaForAllocation() == nullptr && _impl_.audio_frame_ != nullptr) {
    delete _impl_.audio_frame_;
  }
  _impl_.audio_frame_ = nullptr;
}
inline const ::tc::AudioFrame& Message::_internal_audio_frame() const {
  const ::tc::AudioFrame* p = _impl_.audio_frame_;
  return p != nullptr ? *p : reinterpret_cast<const ::tc::AudioFrame&>(
      ::tc::_AudioFrame_default_instance_);
}
inline const ::tc::AudioFrame& Message::audio_frame() const {
  // @@protoc_insertion_point(field_get:tc.Message.audio_frame)
  return _internal_audio_frame();
}
inline void Message::unsafe_arena_set_allocated_audio_frame(
    ::tc::AudioFrame* audio_frame) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.audio_frame_);
  }
  _impl_.audio_frame_ = audio_frame;
  if (audio_frame) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:tc.Message.audio_frame)
}
inline ::tc::AudioFrame* Message::release_audio_frame() {
  
  ::tc::AudioFrame* temp = _impl_.audio_frame_;
  _impl_.audio_frame_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::tc::AudioFrame* Message::unsafe_arena_release_audio_frame() {
  // @@protoc_insertion_point(field_release:tc.Message.audio_frame)
  
  ::tc::AudioFrame* temp = _impl_.audio_frame_;
  _impl_.audio_frame_ = nullptr;
  return temp;
}
inline ::tc::AudioFrame* Message::_internal_mutable_audio_frame() {
  
  if (_impl_.audio_frame_ == nullptr) {
    auto* p = CreateMaybeMessage<::tc::AudioFrame>(GetArenaForAllocation());
    _impl_.audio_frame_ = p;
  }
  return _impl_.audio_frame_;
}
inline ::tc::AudioFrame* Message::mutable_audio_frame() {
  ::tc::AudioFrame* _msg = _internal_mutable_audio_frame();
  // @@protoc_insertion_point(field_mutable:tc.Message.audio_frame)
  return _msg;
}
inline void Message::set_allocated_audio_frame(::tc::AudioFrame* audio_frame) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.audio_frame_;
  }
  if (audio_frame) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(audio_frame);
    if (message_arena != submessage_arena) {
      audio_frame = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, audio_frame, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.audio_frame_ = audio_frame;
  // @@protoc_insertion_point(field_set_allocated:tc.Message.audio_frame)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace tc

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::tc::MessageType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::tc::MessageType>() {
  return ::tc::MessageType_descriptor();
}
template <> struct is_proto_enum< ::tc::VideoType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::tc::VideoType>() {
  return ::tc::VideoType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_tc_5fmessage_2eproto
