// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tc_message.proto

#include "tc_message.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace tc {
PROTOBUF_CONSTEXPR Ack::Ack(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.send_time_)*/uint64_t{0u}
  , /*decltype(_impl_.type_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct AckDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AckDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~AckDefaultTypeInternal() {}
  union {
    Ack _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AckDefaultTypeInternal _Ack_default_instance_;
PROTOBUF_CONSTEXPR Hello::Hello(
    ::_pbi::ConstantInitialized) {}
struct HelloDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HelloDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~HelloDefaultTypeInternal() {}
  union {
    Hello _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HelloDefaultTypeInternal _Hello_default_instance_;
PROTOBUF_CONSTEXPR HeartBeat::HeartBeat(
    ::_pbi::ConstantInitialized) {}
struct HeartBeatDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HeartBeatDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~HeartBeatDefaultTypeInternal() {}
  union {
    HeartBeat _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HeartBeatDefaultTypeInternal _HeartBeat_default_instance_;
PROTOBUF_CONSTEXPR VideoFrame::VideoFrame(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.data_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.type_)*/0
  , /*decltype(_impl_.key_)*/false
  , /*decltype(_impl_.frame_index_)*/uint64_t{0u}
  , /*decltype(_impl_.frame_width_)*/0
  , /*decltype(_impl_.frame_height_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct VideoFrameDefaultTypeInternal {
  PROTOBUF_CONSTEXPR VideoFrameDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~VideoFrameDefaultTypeInternal() {}
  union {
    VideoFrame _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 VideoFrameDefaultTypeInternal _VideoFrame_default_instance_;
PROTOBUF_CONSTEXPR AudioFrame::AudioFrame(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.data_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.samples_)*/0
  , /*decltype(_impl_.channels_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct AudioFrameDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AudioFrameDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~AudioFrameDefaultTypeInternal() {}
  union {
    AudioFrame _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AudioFrameDefaultTypeInternal _AudioFrame_default_instance_;
PROTOBUF_CONSTEXPR KeyEvent::KeyEvent(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.key_code_)*/0u
  , /*decltype(_impl_.down_)*/false
  , /*decltype(_impl_.num_lock_status_)*/0
  , /*decltype(_impl_.caps_lock_status_)*/0
  , /*decltype(_impl_.timestamp_)*/int64_t{0}
  , /*decltype(_impl_.status_check_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct KeyEventDefaultTypeInternal {
  PROTOBUF_CONSTEXPR KeyEventDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~KeyEventDefaultTypeInternal() {}
  union {
    KeyEvent _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 KeyEventDefaultTypeInternal _KeyEvent_default_instance_;
PROTOBUF_CONSTEXPR MouseEvent::MouseEvent(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.monitor_index_)*/0
  , /*decltype(_impl_.x_ratio_)*/0
  , /*decltype(_impl_.y_ratio_)*/0
  , /*decltype(_impl_.button_)*/0
  , /*decltype(_impl_.timestamp_)*/int64_t{0}
  , /*decltype(_impl_.data_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MouseEventDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MouseEventDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MouseEventDefaultTypeInternal() {}
  union {
    MouseEvent _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MouseEventDefaultTypeInternal _MouseEvent_default_instance_;
PROTOBUF_CONSTEXPR Message::Message(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.hello_)*/nullptr
  , /*decltype(_impl_.ack_)*/nullptr
  , /*decltype(_impl_.heart_beat_)*/nullptr
  , /*decltype(_impl_.video_frame_)*/nullptr
  , /*decltype(_impl_.audio_frame_)*/nullptr
  , /*decltype(_impl_.key_event_)*/nullptr
  , /*decltype(_impl_.mouse_event_)*/nullptr
  , /*decltype(_impl_.send_time_)*/uint64_t{0u}
  , /*decltype(_impl_.type_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MessageDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MessageDefaultTypeInternal() {}
  union {
    Message _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MessageDefaultTypeInternal _Message_default_instance_;
}  // namespace tc
static ::_pb::Metadata file_level_metadata_tc_5fmessage_2eproto[8];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_tc_5fmessage_2eproto[4];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_tc_5fmessage_2eproto = nullptr;

const uint32_t TableStruct_tc_5fmessage_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::tc::Ack, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::tc::Ack, _impl_.type_),
  PROTOBUF_FIELD_OFFSET(::tc::Ack, _impl_.send_time_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::tc::Hello, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::tc::HeartBeat, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::tc::VideoFrame, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::tc::VideoFrame, _impl_.type_),
  PROTOBUF_FIELD_OFFSET(::tc::VideoFrame, _impl_.data_),
  PROTOBUF_FIELD_OFFSET(::tc::VideoFrame, _impl_.frame_index_),
  PROTOBUF_FIELD_OFFSET(::tc::VideoFrame, _impl_.key_),
  PROTOBUF_FIELD_OFFSET(::tc::VideoFrame, _impl_.frame_width_),
  PROTOBUF_FIELD_OFFSET(::tc::VideoFrame, _impl_.frame_height_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::tc::AudioFrame, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::tc::AudioFrame, _impl_.samples_),
  PROTOBUF_FIELD_OFFSET(::tc::AudioFrame, _impl_.channels_),
  PROTOBUF_FIELD_OFFSET(::tc::AudioFrame, _impl_.data_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::tc::KeyEvent, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::tc::KeyEvent, _impl_.key_code_),
  PROTOBUF_FIELD_OFFSET(::tc::KeyEvent, _impl_.down_),
  PROTOBUF_FIELD_OFFSET(::tc::KeyEvent, _impl_.num_lock_status_),
  PROTOBUF_FIELD_OFFSET(::tc::KeyEvent, _impl_.caps_lock_status_),
  PROTOBUF_FIELD_OFFSET(::tc::KeyEvent, _impl_.status_check_),
  PROTOBUF_FIELD_OFFSET(::tc::KeyEvent, _impl_.timestamp_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::tc::MouseEvent, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::tc::MouseEvent, _impl_.monitor_index_),
  PROTOBUF_FIELD_OFFSET(::tc::MouseEvent, _impl_.x_ratio_),
  PROTOBUF_FIELD_OFFSET(::tc::MouseEvent, _impl_.y_ratio_),
  PROTOBUF_FIELD_OFFSET(::tc::MouseEvent, _impl_.button_),
  PROTOBUF_FIELD_OFFSET(::tc::MouseEvent, _impl_.data_),
  PROTOBUF_FIELD_OFFSET(::tc::MouseEvent, _impl_.timestamp_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::tc::Message, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::tc::Message, _impl_.type_),
  PROTOBUF_FIELD_OFFSET(::tc::Message, _impl_.send_time_),
  PROTOBUF_FIELD_OFFSET(::tc::Message, _impl_.hello_),
  PROTOBUF_FIELD_OFFSET(::tc::Message, _impl_.ack_),
  PROTOBUF_FIELD_OFFSET(::tc::Message, _impl_.heart_beat_),
  PROTOBUF_FIELD_OFFSET(::tc::Message, _impl_.video_frame_),
  PROTOBUF_FIELD_OFFSET(::tc::Message, _impl_.audio_frame_),
  PROTOBUF_FIELD_OFFSET(::tc::Message, _impl_.key_event_),
  PROTOBUF_FIELD_OFFSET(::tc::Message, _impl_.mouse_event_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::tc::Ack)},
  { 8, -1, -1, sizeof(::tc::Hello)},
  { 14, -1, -1, sizeof(::tc::HeartBeat)},
  { 20, -1, -1, sizeof(::tc::VideoFrame)},
  { 32, -1, -1, sizeof(::tc::AudioFrame)},
  { 41, -1, -1, sizeof(::tc::KeyEvent)},
  { 53, -1, -1, sizeof(::tc::MouseEvent)},
  { 65, -1, -1, sizeof(::tc::Message)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::tc::_Ack_default_instance_._instance,
  &::tc::_Hello_default_instance_._instance,
  &::tc::_HeartBeat_default_instance_._instance,
  &::tc::_VideoFrame_default_instance_._instance,
  &::tc::_AudioFrame_default_instance_._instance,
  &::tc::_KeyEvent_default_instance_._instance,
  &::tc::_MouseEvent_default_instance_._instance,
  &::tc::_Message_default_instance_._instance,
};

const char descriptor_table_protodef_tc_5fmessage_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020tc_message.proto\022\002tc\"7\n\003Ack\022\035\n\004type\030\001 "
  "\001(\0162\017.tc.MessageType\022\021\n\tsend_time\030\002 \001(\004\""
  "\007\n\005Hello\"\013\n\tHeartBeat\"\204\001\n\nVideoFrame\022\033\n\004"
  "type\030\001 \001(\0162\r.tc.VideoType\022\014\n\004data\030\002 \001(\014\022"
  "\023\n\013frame_index\030\003 \001(\004\022\013\n\003key\030\004 \001(\010\022\023\n\013fra"
  "me_width\030\005 \001(\005\022\024\n\014frame_height\030\006 \001(\005\"=\n\n"
  "AudioFrame\022\017\n\007samples\030\001 \001(\005\022\020\n\010channels\030"
  "\002 \001(\005\022\014\n\004data\030\003 \001(\014\"\372\001\n\010KeyEvent\022\020\n\010key_"
  "code\030\001 \001(\r\022\014\n\004down\030\002 \001(\010\022\027\n\017num_lock_sta"
  "tus\030\003 \001(\005\022\030\n\020caps_lock_status\030\004 \001(\005\0225\n\014s"
  "tatus_check\030\005 \001(\0162\037.tc.KeyEvent.LockKeyS"
  "tatusCheck\022\021\n\ttimestamp\030\006 \001(\003\"Q\n\022LockKey"
  "StatusCheck\022\024\n\020kDontCareLockKey\020\000\022\021\n\rkCh"
  "eckNumLock\020\001\022\022\n\016kCheckCapsLock\020\002\"v\n\nMous"
  "eEvent\022\025\n\rmonitor_index\030\001 \001(\005\022\017\n\007x_ratio"
  "\030\002 \001(\002\022\017\n\007y_ratio\030\003 \001(\002\022\016\n\006button\030\004 \001(\005\022"
  "\014\n\004data\030\005 \001(\005\022\021\n\ttimestamp\030\006 \001(\003\"\236\002\n\007Mes"
  "sage\022\035\n\004type\030\001 \001(\0162\017.tc.MessageType\022\021\n\ts"
  "end_time\030\002 \001(\004\022\030\n\005hello\030\003 \001(\0132\t.tc.Hello"
  "\022\024\n\003ack\030\004 \001(\0132\007.tc.Ack\022!\n\nheart_beat\030\005 \001"
  "(\0132\r.tc.HeartBeat\022#\n\013video_frame\030\006 \001(\0132\016"
  ".tc.VideoFrame\022#\n\013audio_frame\030\007 \001(\0132\016.tc"
  ".AudioFrame\022\037\n\tkey_event\030\010 \001(\0132\014.tc.KeyE"
  "vent\022#\n\013mouse_event\030\t \001(\0132\016.tc.MouseEven"
  "t*u\n\013MessageType\022\n\n\006kHello\020\000\022\010\n\004kAck\020\001\022\016"
  "\n\nkHeartBeat\020\002\022\017\n\013kVideoFrame\020\003\022\017\n\013kAudi"
  "oFrame\020\004\022\r\n\tkKeyEvent\020\005\022\017\n\013kMouseEvent\020\006"
  "*4\n\tVideoType\022\014\n\010kNetH264\020\000\022\014\n\010kNetHevc\020"
  "\001\022\013\n\007kNetVp9\020\002*\356\001\n\013EButtonFlag\022\023\n\017kButto"
  "nFlagNone\020\000\022\031\n\025kButtonFlagCapsLockOn\020\001\022\030"
  "\n\024kButtonFlagShiftDown\020\002\022\032\n\026kButtonFlagC"
  "ontrolDown\020\004\022\026\n\022kButtonFlagAltDown\020\010\022\036\n\032"
  "kButtonFlagLeftMouseButton\020\020\022 \n\034kButtonF"
  "lagMiddleMouseButton\020 \022\037\n\033kButtonFlagRig"
  "htMouseButton\020@b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_tc_5fmessage_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_tc_5fmessage_2eproto = {
    false, false, 1383, descriptor_table_protodef_tc_5fmessage_2eproto,
    "tc_message.proto",
    &descriptor_table_tc_5fmessage_2eproto_once, nullptr, 0, 8,
    schemas, file_default_instances, TableStruct_tc_5fmessage_2eproto::offsets,
    file_level_metadata_tc_5fmessage_2eproto, file_level_enum_descriptors_tc_5fmessage_2eproto,
    file_level_service_descriptors_tc_5fmessage_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_tc_5fmessage_2eproto_getter() {
  return &descriptor_table_tc_5fmessage_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_tc_5fmessage_2eproto(&descriptor_table_tc_5fmessage_2eproto);
namespace tc {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* KeyEvent_LockKeyStatusCheck_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_tc_5fmessage_2eproto);
  return file_level_enum_descriptors_tc_5fmessage_2eproto[0];
}
bool KeyEvent_LockKeyStatusCheck_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr KeyEvent_LockKeyStatusCheck KeyEvent::kDontCareLockKey;
constexpr KeyEvent_LockKeyStatusCheck KeyEvent::kCheckNumLock;
constexpr KeyEvent_LockKeyStatusCheck KeyEvent::kCheckCapsLock;
constexpr KeyEvent_LockKeyStatusCheck KeyEvent::LockKeyStatusCheck_MIN;
constexpr KeyEvent_LockKeyStatusCheck KeyEvent::LockKeyStatusCheck_MAX;
constexpr int KeyEvent::LockKeyStatusCheck_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MessageType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_tc_5fmessage_2eproto);
  return file_level_enum_descriptors_tc_5fmessage_2eproto[1];
}
bool MessageType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* VideoType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_tc_5fmessage_2eproto);
  return file_level_enum_descriptors_tc_5fmessage_2eproto[2];
}
bool VideoType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EButtonFlag_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_tc_5fmessage_2eproto);
  return file_level_enum_descriptors_tc_5fmessage_2eproto[3];
}
bool EButtonFlag_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 4:
    case 8:
    case 16:
    case 32:
    case 64:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class Ack::_Internal {
 public:
};

Ack::Ack(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:tc.Ack)
}
Ack::Ack(const Ack& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Ack* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.send_time_){}
    , decltype(_impl_.type_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.send_time_, &from._impl_.send_time_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.type_) -
    reinterpret_cast<char*>(&_impl_.send_time_)) + sizeof(_impl_.type_));
  // @@protoc_insertion_point(copy_constructor:tc.Ack)
}

inline void Ack::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.send_time_){uint64_t{0u}}
    , decltype(_impl_.type_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Ack::~Ack() {
  // @@protoc_insertion_point(destructor:tc.Ack)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Ack::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Ack::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Ack::Clear() {
// @@protoc_insertion_point(message_clear_start:tc.Ack)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.send_time_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.type_) -
      reinterpret_cast<char*>(&_impl_.send_time_)) + sizeof(_impl_.type_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Ack::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .tc.MessageType type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_type(static_cast<::tc::MessageType>(val));
        } else
          goto handle_unusual;
        continue;
      // uint64 send_time = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.send_time_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Ack::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:tc.Ack)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .tc.MessageType type = 1;
  if (this->_internal_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_type(), target);
  }

  // uint64 send_time = 2;
  if (this->_internal_send_time() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(2, this->_internal_send_time(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tc.Ack)
  return target;
}

size_t Ack::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tc.Ack)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 send_time = 2;
  if (this->_internal_send_time() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_send_time());
  }

  // .tc.MessageType type = 1;
  if (this->_internal_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Ack::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Ack::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Ack::GetClassData() const { return &_class_data_; }


void Ack::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Ack*>(&to_msg);
  auto& from = static_cast<const Ack&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:tc.Ack)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_send_time() != 0) {
    _this->_internal_set_send_time(from._internal_send_time());
  }
  if (from._internal_type() != 0) {
    _this->_internal_set_type(from._internal_type());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Ack::CopyFrom(const Ack& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tc.Ack)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Ack::IsInitialized() const {
  return true;
}

void Ack::InternalSwap(Ack* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Ack, _impl_.type_)
      + sizeof(Ack::_impl_.type_)
      - PROTOBUF_FIELD_OFFSET(Ack, _impl_.send_time_)>(
          reinterpret_cast<char*>(&_impl_.send_time_),
          reinterpret_cast<char*>(&other->_impl_.send_time_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Ack::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_tc_5fmessage_2eproto_getter, &descriptor_table_tc_5fmessage_2eproto_once,
      file_level_metadata_tc_5fmessage_2eproto[0]);
}

// ===================================================================

class Hello::_Internal {
 public:
};

Hello::Hello(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:tc.Hello)
}
Hello::Hello(const Hello& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  Hello* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:tc.Hello)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Hello::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Hello::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata Hello::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_tc_5fmessage_2eproto_getter, &descriptor_table_tc_5fmessage_2eproto_once,
      file_level_metadata_tc_5fmessage_2eproto[1]);
}

// ===================================================================

class HeartBeat::_Internal {
 public:
};

HeartBeat::HeartBeat(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:tc.HeartBeat)
}
HeartBeat::HeartBeat(const HeartBeat& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  HeartBeat* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:tc.HeartBeat)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData HeartBeat::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*HeartBeat::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata HeartBeat::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_tc_5fmessage_2eproto_getter, &descriptor_table_tc_5fmessage_2eproto_once,
      file_level_metadata_tc_5fmessage_2eproto[2]);
}

// ===================================================================

class VideoFrame::_Internal {
 public:
};

VideoFrame::VideoFrame(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:tc.VideoFrame)
}
VideoFrame::VideoFrame(const VideoFrame& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  VideoFrame* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.data_){}
    , decltype(_impl_.type_){}
    , decltype(_impl_.key_){}
    , decltype(_impl_.frame_index_){}
    , decltype(_impl_.frame_width_){}
    , decltype(_impl_.frame_height_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_data().empty()) {
    _this->_impl_.data_.Set(from._internal_data(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.type_, &from._impl_.type_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.frame_height_) -
    reinterpret_cast<char*>(&_impl_.type_)) + sizeof(_impl_.frame_height_));
  // @@protoc_insertion_point(copy_constructor:tc.VideoFrame)
}

inline void VideoFrame::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.data_){}
    , decltype(_impl_.type_){0}
    , decltype(_impl_.key_){false}
    , decltype(_impl_.frame_index_){uint64_t{0u}}
    , decltype(_impl_.frame_width_){0}
    , decltype(_impl_.frame_height_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

VideoFrame::~VideoFrame() {
  // @@protoc_insertion_point(destructor:tc.VideoFrame)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void VideoFrame::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.data_.Destroy();
}

void VideoFrame::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void VideoFrame::Clear() {
// @@protoc_insertion_point(message_clear_start:tc.VideoFrame)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.data_.ClearToEmpty();
  ::memset(&_impl_.type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.frame_height_) -
      reinterpret_cast<char*>(&_impl_.type_)) + sizeof(_impl_.frame_height_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* VideoFrame::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .tc.VideoType type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_type(static_cast<::tc::VideoType>(val));
        } else
          goto handle_unusual;
        continue;
      // bytes data = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_data();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 frame_index = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.frame_index_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool key = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.key_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 frame_width = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.frame_width_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 frame_height = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.frame_height_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* VideoFrame::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:tc.VideoFrame)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .tc.VideoType type = 1;
  if (this->_internal_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_type(), target);
  }

  // bytes data = 2;
  if (!this->_internal_data().empty()) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_data(), target);
  }

  // uint64 frame_index = 3;
  if (this->_internal_frame_index() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(3, this->_internal_frame_index(), target);
  }

  // bool key = 4;
  if (this->_internal_key() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(4, this->_internal_key(), target);
  }

  // int32 frame_width = 5;
  if (this->_internal_frame_width() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(5, this->_internal_frame_width(), target);
  }

  // int32 frame_height = 6;
  if (this->_internal_frame_height() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(6, this->_internal_frame_height(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tc.VideoFrame)
  return target;
}

size_t VideoFrame::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tc.VideoFrame)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes data = 2;
  if (!this->_internal_data().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_data());
  }

  // .tc.VideoType type = 1;
  if (this->_internal_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_type());
  }

  // bool key = 4;
  if (this->_internal_key() != 0) {
    total_size += 1 + 1;
  }

  // uint64 frame_index = 3;
  if (this->_internal_frame_index() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_frame_index());
  }

  // int32 frame_width = 5;
  if (this->_internal_frame_width() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_frame_width());
  }

  // int32 frame_height = 6;
  if (this->_internal_frame_height() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_frame_height());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData VideoFrame::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    VideoFrame::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*VideoFrame::GetClassData() const { return &_class_data_; }


void VideoFrame::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<VideoFrame*>(&to_msg);
  auto& from = static_cast<const VideoFrame&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:tc.VideoFrame)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_data().empty()) {
    _this->_internal_set_data(from._internal_data());
  }
  if (from._internal_type() != 0) {
    _this->_internal_set_type(from._internal_type());
  }
  if (from._internal_key() != 0) {
    _this->_internal_set_key(from._internal_key());
  }
  if (from._internal_frame_index() != 0) {
    _this->_internal_set_frame_index(from._internal_frame_index());
  }
  if (from._internal_frame_width() != 0) {
    _this->_internal_set_frame_width(from._internal_frame_width());
  }
  if (from._internal_frame_height() != 0) {
    _this->_internal_set_frame_height(from._internal_frame_height());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void VideoFrame::CopyFrom(const VideoFrame& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tc.VideoFrame)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool VideoFrame::IsInitialized() const {
  return true;
}

void VideoFrame::InternalSwap(VideoFrame* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.data_, lhs_arena,
      &other->_impl_.data_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(VideoFrame, _impl_.frame_height_)
      + sizeof(VideoFrame::_impl_.frame_height_)
      - PROTOBUF_FIELD_OFFSET(VideoFrame, _impl_.type_)>(
          reinterpret_cast<char*>(&_impl_.type_),
          reinterpret_cast<char*>(&other->_impl_.type_));
}

::PROTOBUF_NAMESPACE_ID::Metadata VideoFrame::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_tc_5fmessage_2eproto_getter, &descriptor_table_tc_5fmessage_2eproto_once,
      file_level_metadata_tc_5fmessage_2eproto[3]);
}

// ===================================================================

class AudioFrame::_Internal {
 public:
};

AudioFrame::AudioFrame(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:tc.AudioFrame)
}
AudioFrame::AudioFrame(const AudioFrame& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  AudioFrame* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.data_){}
    , decltype(_impl_.samples_){}
    , decltype(_impl_.channels_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_data().empty()) {
    _this->_impl_.data_.Set(from._internal_data(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.samples_, &from._impl_.samples_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.channels_) -
    reinterpret_cast<char*>(&_impl_.samples_)) + sizeof(_impl_.channels_));
  // @@protoc_insertion_point(copy_constructor:tc.AudioFrame)
}

inline void AudioFrame::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.data_){}
    , decltype(_impl_.samples_){0}
    , decltype(_impl_.channels_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

AudioFrame::~AudioFrame() {
  // @@protoc_insertion_point(destructor:tc.AudioFrame)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void AudioFrame::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.data_.Destroy();
}

void AudioFrame::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void AudioFrame::Clear() {
// @@protoc_insertion_point(message_clear_start:tc.AudioFrame)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.data_.ClearToEmpty();
  ::memset(&_impl_.samples_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.channels_) -
      reinterpret_cast<char*>(&_impl_.samples_)) + sizeof(_impl_.channels_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AudioFrame::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 samples = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.samples_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 channels = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.channels_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes data = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_data();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* AudioFrame::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:tc.AudioFrame)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 samples = 1;
  if (this->_internal_samples() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_samples(), target);
  }

  // int32 channels = 2;
  if (this->_internal_channels() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_channels(), target);
  }

  // bytes data = 3;
  if (!this->_internal_data().empty()) {
    target = stream->WriteBytesMaybeAliased(
        3, this->_internal_data(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tc.AudioFrame)
  return target;
}

size_t AudioFrame::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tc.AudioFrame)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes data = 3;
  if (!this->_internal_data().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_data());
  }

  // int32 samples = 1;
  if (this->_internal_samples() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_samples());
  }

  // int32 channels = 2;
  if (this->_internal_channels() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_channels());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AudioFrame::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    AudioFrame::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AudioFrame::GetClassData() const { return &_class_data_; }


void AudioFrame::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<AudioFrame*>(&to_msg);
  auto& from = static_cast<const AudioFrame&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:tc.AudioFrame)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_data().empty()) {
    _this->_internal_set_data(from._internal_data());
  }
  if (from._internal_samples() != 0) {
    _this->_internal_set_samples(from._internal_samples());
  }
  if (from._internal_channels() != 0) {
    _this->_internal_set_channels(from._internal_channels());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AudioFrame::CopyFrom(const AudioFrame& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tc.AudioFrame)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AudioFrame::IsInitialized() const {
  return true;
}

void AudioFrame::InternalSwap(AudioFrame* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.data_, lhs_arena,
      &other->_impl_.data_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AudioFrame, _impl_.channels_)
      + sizeof(AudioFrame::_impl_.channels_)
      - PROTOBUF_FIELD_OFFSET(AudioFrame, _impl_.samples_)>(
          reinterpret_cast<char*>(&_impl_.samples_),
          reinterpret_cast<char*>(&other->_impl_.samples_));
}

::PROTOBUF_NAMESPACE_ID::Metadata AudioFrame::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_tc_5fmessage_2eproto_getter, &descriptor_table_tc_5fmessage_2eproto_once,
      file_level_metadata_tc_5fmessage_2eproto[4]);
}

// ===================================================================

class KeyEvent::_Internal {
 public:
};

KeyEvent::KeyEvent(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:tc.KeyEvent)
}
KeyEvent::KeyEvent(const KeyEvent& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  KeyEvent* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.key_code_){}
    , decltype(_impl_.down_){}
    , decltype(_impl_.num_lock_status_){}
    , decltype(_impl_.caps_lock_status_){}
    , decltype(_impl_.timestamp_){}
    , decltype(_impl_.status_check_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.key_code_, &from._impl_.key_code_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.status_check_) -
    reinterpret_cast<char*>(&_impl_.key_code_)) + sizeof(_impl_.status_check_));
  // @@protoc_insertion_point(copy_constructor:tc.KeyEvent)
}

inline void KeyEvent::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.key_code_){0u}
    , decltype(_impl_.down_){false}
    , decltype(_impl_.num_lock_status_){0}
    , decltype(_impl_.caps_lock_status_){0}
    , decltype(_impl_.timestamp_){int64_t{0}}
    , decltype(_impl_.status_check_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

KeyEvent::~KeyEvent() {
  // @@protoc_insertion_point(destructor:tc.KeyEvent)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void KeyEvent::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void KeyEvent::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void KeyEvent::Clear() {
// @@protoc_insertion_point(message_clear_start:tc.KeyEvent)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.key_code_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.status_check_) -
      reinterpret_cast<char*>(&_impl_.key_code_)) + sizeof(_impl_.status_check_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* KeyEvent::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 key_code = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.key_code_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool down = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.down_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 num_lock_status = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.num_lock_status_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 caps_lock_status = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.caps_lock_status_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .tc.KeyEvent.LockKeyStatusCheck status_check = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_status_check(static_cast<::tc::KeyEvent_LockKeyStatusCheck>(val));
        } else
          goto handle_unusual;
        continue;
      // int64 timestamp = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.timestamp_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* KeyEvent::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:tc.KeyEvent)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 key_code = 1;
  if (this->_internal_key_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_key_code(), target);
  }

  // bool down = 2;
  if (this->_internal_down() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(2, this->_internal_down(), target);
  }

  // int32 num_lock_status = 3;
  if (this->_internal_num_lock_status() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_num_lock_status(), target);
  }

  // int32 caps_lock_status = 4;
  if (this->_internal_caps_lock_status() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_caps_lock_status(), target);
  }

  // .tc.KeyEvent.LockKeyStatusCheck status_check = 5;
  if (this->_internal_status_check() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      5, this->_internal_status_check(), target);
  }

  // int64 timestamp = 6;
  if (this->_internal_timestamp() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(6, this->_internal_timestamp(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tc.KeyEvent)
  return target;
}

size_t KeyEvent::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tc.KeyEvent)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 key_code = 1;
  if (this->_internal_key_code() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_key_code());
  }

  // bool down = 2;
  if (this->_internal_down() != 0) {
    total_size += 1 + 1;
  }

  // int32 num_lock_status = 3;
  if (this->_internal_num_lock_status() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_num_lock_status());
  }

  // int32 caps_lock_status = 4;
  if (this->_internal_caps_lock_status() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_caps_lock_status());
  }

  // int64 timestamp = 6;
  if (this->_internal_timestamp() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_timestamp());
  }

  // .tc.KeyEvent.LockKeyStatusCheck status_check = 5;
  if (this->_internal_status_check() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_status_check());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData KeyEvent::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    KeyEvent::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*KeyEvent::GetClassData() const { return &_class_data_; }


void KeyEvent::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<KeyEvent*>(&to_msg);
  auto& from = static_cast<const KeyEvent&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:tc.KeyEvent)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_key_code() != 0) {
    _this->_internal_set_key_code(from._internal_key_code());
  }
  if (from._internal_down() != 0) {
    _this->_internal_set_down(from._internal_down());
  }
  if (from._internal_num_lock_status() != 0) {
    _this->_internal_set_num_lock_status(from._internal_num_lock_status());
  }
  if (from._internal_caps_lock_status() != 0) {
    _this->_internal_set_caps_lock_status(from._internal_caps_lock_status());
  }
  if (from._internal_timestamp() != 0) {
    _this->_internal_set_timestamp(from._internal_timestamp());
  }
  if (from._internal_status_check() != 0) {
    _this->_internal_set_status_check(from._internal_status_check());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void KeyEvent::CopyFrom(const KeyEvent& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tc.KeyEvent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool KeyEvent::IsInitialized() const {
  return true;
}

void KeyEvent::InternalSwap(KeyEvent* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(KeyEvent, _impl_.status_check_)
      + sizeof(KeyEvent::_impl_.status_check_)
      - PROTOBUF_FIELD_OFFSET(KeyEvent, _impl_.key_code_)>(
          reinterpret_cast<char*>(&_impl_.key_code_),
          reinterpret_cast<char*>(&other->_impl_.key_code_));
}

::PROTOBUF_NAMESPACE_ID::Metadata KeyEvent::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_tc_5fmessage_2eproto_getter, &descriptor_table_tc_5fmessage_2eproto_once,
      file_level_metadata_tc_5fmessage_2eproto[5]);
}

// ===================================================================

class MouseEvent::_Internal {
 public:
};

MouseEvent::MouseEvent(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:tc.MouseEvent)
}
MouseEvent::MouseEvent(const MouseEvent& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MouseEvent* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.monitor_index_){}
    , decltype(_impl_.x_ratio_){}
    , decltype(_impl_.y_ratio_){}
    , decltype(_impl_.button_){}
    , decltype(_impl_.timestamp_){}
    , decltype(_impl_.data_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.monitor_index_, &from._impl_.monitor_index_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.data_) -
    reinterpret_cast<char*>(&_impl_.monitor_index_)) + sizeof(_impl_.data_));
  // @@protoc_insertion_point(copy_constructor:tc.MouseEvent)
}

inline void MouseEvent::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.monitor_index_){0}
    , decltype(_impl_.x_ratio_){0}
    , decltype(_impl_.y_ratio_){0}
    , decltype(_impl_.button_){0}
    , decltype(_impl_.timestamp_){int64_t{0}}
    , decltype(_impl_.data_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

MouseEvent::~MouseEvent() {
  // @@protoc_insertion_point(destructor:tc.MouseEvent)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MouseEvent::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void MouseEvent::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MouseEvent::Clear() {
// @@protoc_insertion_point(message_clear_start:tc.MouseEvent)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.monitor_index_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.data_) -
      reinterpret_cast<char*>(&_impl_.monitor_index_)) + sizeof(_impl_.data_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MouseEvent::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 monitor_index = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.monitor_index_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // float x_ratio = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 21)) {
          _impl_.x_ratio_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float y_ratio = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 29)) {
          _impl_.y_ratio_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // int32 button = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.button_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 data = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.data_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 timestamp = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.timestamp_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* MouseEvent::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:tc.MouseEvent)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 monitor_index = 1;
  if (this->_internal_monitor_index() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_monitor_index(), target);
  }

  // float x_ratio = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_x_ratio = this->_internal_x_ratio();
  uint32_t raw_x_ratio;
  memcpy(&raw_x_ratio, &tmp_x_ratio, sizeof(tmp_x_ratio));
  if (raw_x_ratio != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(2, this->_internal_x_ratio(), target);
  }

  // float y_ratio = 3;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_y_ratio = this->_internal_y_ratio();
  uint32_t raw_y_ratio;
  memcpy(&raw_y_ratio, &tmp_y_ratio, sizeof(tmp_y_ratio));
  if (raw_y_ratio != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(3, this->_internal_y_ratio(), target);
  }

  // int32 button = 4;
  if (this->_internal_button() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_button(), target);
  }

  // int32 data = 5;
  if (this->_internal_data() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(5, this->_internal_data(), target);
  }

  // int64 timestamp = 6;
  if (this->_internal_timestamp() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(6, this->_internal_timestamp(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tc.MouseEvent)
  return target;
}

size_t MouseEvent::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tc.MouseEvent)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 monitor_index = 1;
  if (this->_internal_monitor_index() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_monitor_index());
  }

  // float x_ratio = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_x_ratio = this->_internal_x_ratio();
  uint32_t raw_x_ratio;
  memcpy(&raw_x_ratio, &tmp_x_ratio, sizeof(tmp_x_ratio));
  if (raw_x_ratio != 0) {
    total_size += 1 + 4;
  }

  // float y_ratio = 3;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_y_ratio = this->_internal_y_ratio();
  uint32_t raw_y_ratio;
  memcpy(&raw_y_ratio, &tmp_y_ratio, sizeof(tmp_y_ratio));
  if (raw_y_ratio != 0) {
    total_size += 1 + 4;
  }

  // int32 button = 4;
  if (this->_internal_button() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_button());
  }

  // int64 timestamp = 6;
  if (this->_internal_timestamp() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_timestamp());
  }

  // int32 data = 5;
  if (this->_internal_data() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_data());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MouseEvent::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    MouseEvent::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MouseEvent::GetClassData() const { return &_class_data_; }


void MouseEvent::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<MouseEvent*>(&to_msg);
  auto& from = static_cast<const MouseEvent&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:tc.MouseEvent)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_monitor_index() != 0) {
    _this->_internal_set_monitor_index(from._internal_monitor_index());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_x_ratio = from._internal_x_ratio();
  uint32_t raw_x_ratio;
  memcpy(&raw_x_ratio, &tmp_x_ratio, sizeof(tmp_x_ratio));
  if (raw_x_ratio != 0) {
    _this->_internal_set_x_ratio(from._internal_x_ratio());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_y_ratio = from._internal_y_ratio();
  uint32_t raw_y_ratio;
  memcpy(&raw_y_ratio, &tmp_y_ratio, sizeof(tmp_y_ratio));
  if (raw_y_ratio != 0) {
    _this->_internal_set_y_ratio(from._internal_y_ratio());
  }
  if (from._internal_button() != 0) {
    _this->_internal_set_button(from._internal_button());
  }
  if (from._internal_timestamp() != 0) {
    _this->_internal_set_timestamp(from._internal_timestamp());
  }
  if (from._internal_data() != 0) {
    _this->_internal_set_data(from._internal_data());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void MouseEvent::CopyFrom(const MouseEvent& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tc.MouseEvent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MouseEvent::IsInitialized() const {
  return true;
}

void MouseEvent::InternalSwap(MouseEvent* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MouseEvent, _impl_.data_)
      + sizeof(MouseEvent::_impl_.data_)
      - PROTOBUF_FIELD_OFFSET(MouseEvent, _impl_.monitor_index_)>(
          reinterpret_cast<char*>(&_impl_.monitor_index_),
          reinterpret_cast<char*>(&other->_impl_.monitor_index_));
}

::PROTOBUF_NAMESPACE_ID::Metadata MouseEvent::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_tc_5fmessage_2eproto_getter, &descriptor_table_tc_5fmessage_2eproto_once,
      file_level_metadata_tc_5fmessage_2eproto[6]);
}

// ===================================================================

class Message::_Internal {
 public:
  static const ::tc::Hello& hello(const Message* msg);
  static const ::tc::Ack& ack(const Message* msg);
  static const ::tc::HeartBeat& heart_beat(const Message* msg);
  static const ::tc::VideoFrame& video_frame(const Message* msg);
  static const ::tc::AudioFrame& audio_frame(const Message* msg);
  static const ::tc::KeyEvent& key_event(const Message* msg);
  static const ::tc::MouseEvent& mouse_event(const Message* msg);
};

const ::tc::Hello&
Message::_Internal::hello(const Message* msg) {
  return *msg->_impl_.hello_;
}
const ::tc::Ack&
Message::_Internal::ack(const Message* msg) {
  return *msg->_impl_.ack_;
}
const ::tc::HeartBeat&
Message::_Internal::heart_beat(const Message* msg) {
  return *msg->_impl_.heart_beat_;
}
const ::tc::VideoFrame&
Message::_Internal::video_frame(const Message* msg) {
  return *msg->_impl_.video_frame_;
}
const ::tc::AudioFrame&
Message::_Internal::audio_frame(const Message* msg) {
  return *msg->_impl_.audio_frame_;
}
const ::tc::KeyEvent&
Message::_Internal::key_event(const Message* msg) {
  return *msg->_impl_.key_event_;
}
const ::tc::MouseEvent&
Message::_Internal::mouse_event(const Message* msg) {
  return *msg->_impl_.mouse_event_;
}
Message::Message(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:tc.Message)
}
Message::Message(const Message& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Message* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.hello_){nullptr}
    , decltype(_impl_.ack_){nullptr}
    , decltype(_impl_.heart_beat_){nullptr}
    , decltype(_impl_.video_frame_){nullptr}
    , decltype(_impl_.audio_frame_){nullptr}
    , decltype(_impl_.key_event_){nullptr}
    , decltype(_impl_.mouse_event_){nullptr}
    , decltype(_impl_.send_time_){}
    , decltype(_impl_.type_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_hello()) {
    _this->_impl_.hello_ = new ::tc::Hello(*from._impl_.hello_);
  }
  if (from._internal_has_ack()) {
    _this->_impl_.ack_ = new ::tc::Ack(*from._impl_.ack_);
  }
  if (from._internal_has_heart_beat()) {
    _this->_impl_.heart_beat_ = new ::tc::HeartBeat(*from._impl_.heart_beat_);
  }
  if (from._internal_has_video_frame()) {
    _this->_impl_.video_frame_ = new ::tc::VideoFrame(*from._impl_.video_frame_);
  }
  if (from._internal_has_audio_frame()) {
    _this->_impl_.audio_frame_ = new ::tc::AudioFrame(*from._impl_.audio_frame_);
  }
  if (from._internal_has_key_event()) {
    _this->_impl_.key_event_ = new ::tc::KeyEvent(*from._impl_.key_event_);
  }
  if (from._internal_has_mouse_event()) {
    _this->_impl_.mouse_event_ = new ::tc::MouseEvent(*from._impl_.mouse_event_);
  }
  ::memcpy(&_impl_.send_time_, &from._impl_.send_time_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.type_) -
    reinterpret_cast<char*>(&_impl_.send_time_)) + sizeof(_impl_.type_));
  // @@protoc_insertion_point(copy_constructor:tc.Message)
}

inline void Message::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.hello_){nullptr}
    , decltype(_impl_.ack_){nullptr}
    , decltype(_impl_.heart_beat_){nullptr}
    , decltype(_impl_.video_frame_){nullptr}
    , decltype(_impl_.audio_frame_){nullptr}
    , decltype(_impl_.key_event_){nullptr}
    , decltype(_impl_.mouse_event_){nullptr}
    , decltype(_impl_.send_time_){uint64_t{0u}}
    , decltype(_impl_.type_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Message::~Message() {
  // @@protoc_insertion_point(destructor:tc.Message)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Message::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.hello_;
  if (this != internal_default_instance()) delete _impl_.ack_;
  if (this != internal_default_instance()) delete _impl_.heart_beat_;
  if (this != internal_default_instance()) delete _impl_.video_frame_;
  if (this != internal_default_instance()) delete _impl_.audio_frame_;
  if (this != internal_default_instance()) delete _impl_.key_event_;
  if (this != internal_default_instance()) delete _impl_.mouse_event_;
}

void Message::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Message::Clear() {
// @@protoc_insertion_point(message_clear_start:tc.Message)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.hello_ != nullptr) {
    delete _impl_.hello_;
  }
  _impl_.hello_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.ack_ != nullptr) {
    delete _impl_.ack_;
  }
  _impl_.ack_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.heart_beat_ != nullptr) {
    delete _impl_.heart_beat_;
  }
  _impl_.heart_beat_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.video_frame_ != nullptr) {
    delete _impl_.video_frame_;
  }
  _impl_.video_frame_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.audio_frame_ != nullptr) {
    delete _impl_.audio_frame_;
  }
  _impl_.audio_frame_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.key_event_ != nullptr) {
    delete _impl_.key_event_;
  }
  _impl_.key_event_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.mouse_event_ != nullptr) {
    delete _impl_.mouse_event_;
  }
  _impl_.mouse_event_ = nullptr;
  ::memset(&_impl_.send_time_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.type_) -
      reinterpret_cast<char*>(&_impl_.send_time_)) + sizeof(_impl_.type_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Message::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .tc.MessageType type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_type(static_cast<::tc::MessageType>(val));
        } else
          goto handle_unusual;
        continue;
      // uint64 send_time = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.send_time_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .tc.Hello hello = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_hello(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .tc.Ack ack = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_ack(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .tc.HeartBeat heart_beat = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_heart_beat(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .tc.VideoFrame video_frame = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          ptr = ctx->ParseMessage(_internal_mutable_video_frame(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .tc.AudioFrame audio_frame = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          ptr = ctx->ParseMessage(_internal_mutable_audio_frame(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .tc.KeyEvent key_event = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          ptr = ctx->ParseMessage(_internal_mutable_key_event(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .tc.MouseEvent mouse_event = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 74)) {
          ptr = ctx->ParseMessage(_internal_mutable_mouse_event(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Message::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:tc.Message)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .tc.MessageType type = 1;
  if (this->_internal_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_type(), target);
  }

  // uint64 send_time = 2;
  if (this->_internal_send_time() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(2, this->_internal_send_time(), target);
  }

  // .tc.Hello hello = 3;
  if (this->_internal_has_hello()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::hello(this),
        _Internal::hello(this).GetCachedSize(), target, stream);
  }

  // .tc.Ack ack = 4;
  if (this->_internal_has_ack()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::ack(this),
        _Internal::ack(this).GetCachedSize(), target, stream);
  }

  // .tc.HeartBeat heart_beat = 5;
  if (this->_internal_has_heart_beat()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, _Internal::heart_beat(this),
        _Internal::heart_beat(this).GetCachedSize(), target, stream);
  }

  // .tc.VideoFrame video_frame = 6;
  if (this->_internal_has_video_frame()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(6, _Internal::video_frame(this),
        _Internal::video_frame(this).GetCachedSize(), target, stream);
  }

  // .tc.AudioFrame audio_frame = 7;
  if (this->_internal_has_audio_frame()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(7, _Internal::audio_frame(this),
        _Internal::audio_frame(this).GetCachedSize(), target, stream);
  }

  // .tc.KeyEvent key_event = 8;
  if (this->_internal_has_key_event()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(8, _Internal::key_event(this),
        _Internal::key_event(this).GetCachedSize(), target, stream);
  }

  // .tc.MouseEvent mouse_event = 9;
  if (this->_internal_has_mouse_event()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(9, _Internal::mouse_event(this),
        _Internal::mouse_event(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tc.Message)
  return target;
}

size_t Message::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tc.Message)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .tc.Hello hello = 3;
  if (this->_internal_has_hello()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.hello_);
  }

  // .tc.Ack ack = 4;
  if (this->_internal_has_ack()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.ack_);
  }

  // .tc.HeartBeat heart_beat = 5;
  if (this->_internal_has_heart_beat()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.heart_beat_);
  }

  // .tc.VideoFrame video_frame = 6;
  if (this->_internal_has_video_frame()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.video_frame_);
  }

  // .tc.AudioFrame audio_frame = 7;
  if (this->_internal_has_audio_frame()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.audio_frame_);
  }

  // .tc.KeyEvent key_event = 8;
  if (this->_internal_has_key_event()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.key_event_);
  }

  // .tc.MouseEvent mouse_event = 9;
  if (this->_internal_has_mouse_event()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.mouse_event_);
  }

  // uint64 send_time = 2;
  if (this->_internal_send_time() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_send_time());
  }

  // .tc.MessageType type = 1;
  if (this->_internal_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Message::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Message::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Message::GetClassData() const { return &_class_data_; }


void Message::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Message*>(&to_msg);
  auto& from = static_cast<const Message&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:tc.Message)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_hello()) {
    _this->_internal_mutable_hello()->::tc::Hello::MergeFrom(
        from._internal_hello());
  }
  if (from._internal_has_ack()) {
    _this->_internal_mutable_ack()->::tc::Ack::MergeFrom(
        from._internal_ack());
  }
  if (from._internal_has_heart_beat()) {
    _this->_internal_mutable_heart_beat()->::tc::HeartBeat::MergeFrom(
        from._internal_heart_beat());
  }
  if (from._internal_has_video_frame()) {
    _this->_internal_mutable_video_frame()->::tc::VideoFrame::MergeFrom(
        from._internal_video_frame());
  }
  if (from._internal_has_audio_frame()) {
    _this->_internal_mutable_audio_frame()->::tc::AudioFrame::MergeFrom(
        from._internal_audio_frame());
  }
  if (from._internal_has_key_event()) {
    _this->_internal_mutable_key_event()->::tc::KeyEvent::MergeFrom(
        from._internal_key_event());
  }
  if (from._internal_has_mouse_event()) {
    _this->_internal_mutable_mouse_event()->::tc::MouseEvent::MergeFrom(
        from._internal_mouse_event());
  }
  if (from._internal_send_time() != 0) {
    _this->_internal_set_send_time(from._internal_send_time());
  }
  if (from._internal_type() != 0) {
    _this->_internal_set_type(from._internal_type());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Message::CopyFrom(const Message& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tc.Message)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Message::IsInitialized() const {
  return true;
}

void Message::InternalSwap(Message* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Message, _impl_.type_)
      + sizeof(Message::_impl_.type_)
      - PROTOBUF_FIELD_OFFSET(Message, _impl_.hello_)>(
          reinterpret_cast<char*>(&_impl_.hello_),
          reinterpret_cast<char*>(&other->_impl_.hello_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Message::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_tc_5fmessage_2eproto_getter, &descriptor_table_tc_5fmessage_2eproto_once,
      file_level_metadata_tc_5fmessage_2eproto[7]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace tc
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::tc::Ack*
Arena::CreateMaybeMessage< ::tc::Ack >(Arena* arena) {
  return Arena::CreateMessageInternal< ::tc::Ack >(arena);
}
template<> PROTOBUF_NOINLINE ::tc::Hello*
Arena::CreateMaybeMessage< ::tc::Hello >(Arena* arena) {
  return Arena::CreateMessageInternal< ::tc::Hello >(arena);
}
template<> PROTOBUF_NOINLINE ::tc::HeartBeat*
Arena::CreateMaybeMessage< ::tc::HeartBeat >(Arena* arena) {
  return Arena::CreateMessageInternal< ::tc::HeartBeat >(arena);
}
template<> PROTOBUF_NOINLINE ::tc::VideoFrame*
Arena::CreateMaybeMessage< ::tc::VideoFrame >(Arena* arena) {
  return Arena::CreateMessageInternal< ::tc::VideoFrame >(arena);
}
template<> PROTOBUF_NOINLINE ::tc::AudioFrame*
Arena::CreateMaybeMessage< ::tc::AudioFrame >(Arena* arena) {
  return Arena::CreateMessageInternal< ::tc::AudioFrame >(arena);
}
template<> PROTOBUF_NOINLINE ::tc::KeyEvent*
Arena::CreateMaybeMessage< ::tc::KeyEvent >(Arena* arena) {
  return Arena::CreateMessageInternal< ::tc::KeyEvent >(arena);
}
template<> PROTOBUF_NOINLINE ::tc::MouseEvent*
Arena::CreateMaybeMessage< ::tc::MouseEvent >(Arena* arena) {
  return Arena::CreateMessageInternal< ::tc::MouseEvent >(arena);
}
template<> PROTOBUF_NOINLINE ::tc::Message*
Arena::CreateMaybeMessage< ::tc::Message >(Arena* arena) {
  return Arena::CreateMessageInternal< ::tc::Message >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
